<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GerenciadorDeFinancas.Application\GerenciadorDeFinancas.Application.csproj" />
    <ProjectReference Include="..\GerenciadorDeFinancas.Domain\GerenciadorDeFinancas.Domain.csproj" />
  </ItemGroup>

</Project>
